//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_UI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu_UI()
        {
            this.Menu_UI_Roles = new HashSet<Menu_UI_Roles>();
        }
    
        public int ID { get; set; }
        public string Element_Name { get; set; }
        public string Element_Controller { get; set; }
        public string Element_Action { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public int Display_Order { get; set; }
        public bool Active { get; set; }
        public string Icon { get; set; }
        public System.DateTime Created_At { get; set; }
        public string Created_By { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu_UI_Roles> Menu_UI_Roles { get; set; }
    }
}
