//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTS.DAL
{
    using System;
    
    public partial class SP_Widget_Display_Tasks_Result1
    {
        public long ID { get; set; }
        public string Area_Title { get; set; }
        public string Region_Title { get; set; }
        public string task_status { get; set; }
    }
}
