//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Status
    {
        public long ID { get; set; }
        public long Task_ID { get; set; }
        public byte Task_Generic_Status_ID { get; set; }
        public System.DateTime Expected_Start_Time { get; set; }
        public System.DateTime Expected_End_Time { get; set; }
        public Nullable<System.DateTime> Actual_Start_Time { get; set; }
        public Nullable<System.DateTime> Actual_End_Time { get; set; }
        public string Ordered_By { get; set; }
        public string Ordered_To { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Task_Generic_Status Task_Generic_Status { get; set; }
    }
}
