//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Fees
    {
        public long ID { get; set; }
        public long Task_ID { get; set; }
        public byte Fees_Type { get; set; }
        public decimal Fees_Amount { get; set; }
        public decimal Fees_Discount { get; set; }
        public string Created_By { get; set; }
        public string Created_At { get; set; }
        public bool Deleted { get; set; }
        public bool Collected { get; set; }
        public decimal Expected_Fees_Amount { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
