//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Task_Fees = new HashSet<Task_Fees>();
            this.Task_Items = new HashSet<Task_Items>();
            this.Task_Status = new HashSet<Task_Status>();
        }
    
        public long ID { get; set; }
        public int Project_ID { get; set; }
        public string Task_Title { get; set; }
        public string Task_External_Ref { get; set; }
        public string Task_Internal_Ref { get; set; }
        public bool Task_Is_Closed { get; set; }
        public string Task_Created_By { get; set; }
        public string Task_Account_Name { get; set; }
        public int Task_Area { get; set; }
        public System.DateTime Due_Date { get; set; }
        public string Task_Shipping_Address { get; set; }
        public string Task_Authorized_Person { get; set; }
        public string Task_Authorized_Email { get; set; }
        public string Task_Authorized_Phone { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Fees> Task_Fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Items> Task_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Status> Task_Status { get; set; }
    }
}
