//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Items
    {
        public long ID { get; set; }
        public Nullable<long> Task_ID { get; set; }
        public string Item_SN { get; set; }
        public string Item_Title { get; set; }
        public string Item_Desc { get; set; }
        public string Item_Weight { get; set; }
        public byte Item_Delivery_Status { get; set; }
        public string Item_Notes { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Created_At { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
