//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Items
    {
        public long ID { get; set; }
        public long Invoice_ID { get; set; }
        public long Item_PriceList_ID { get; set; }
        public decimal Amount { get; set; }
        public decimal Unit_Selling_Price { get; set; }
        public decimal Total_Selling_Price { get; set; }
        public decimal Unit_Cost { get; set; }
        public decimal Discount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item_PriceList Item_PriceList { get; set; }
    }
}
