//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_PriceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_PriceList()
        {
            this.Invoice_Items = new HashSet<Invoice_Items>();
        }
    
        public long ID { get; set; }
        public int Item_Measure_Unit_ID { get; set; }
        public decimal Cost { get; set; }
        public decimal Selling_Price { get; set; }
        public System.DateTime Valid_From { get; set; }
        public System.DateTime Valid_To { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice_Items> Invoice_Items { get; set; }
        public virtual Item_Measures Item_Measures { get; set; }
    }
}
