//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Measures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_Measures()
        {
            this.Item_PriceList = new HashSet<Item_PriceList>();
        }
    
        public int ID { get; set; }
        public int Item_ID { get; set; }
        public byte Measure_Unit { get; set; }
        public Nullable<byte> Parent_Measure_Unit { get; set; }
        public decimal Rate { get; set; }
        public bool Active { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_PriceList> Item_PriceList { get; set; }
    }
}
