//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Noks_POSEntities : DbContext
    {
        public Noks_POSEntities()
            : base("name=Noks_POSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Invoice_Items> Invoice_Items { get; set; }
        public virtual DbSet<POS_Sessions> POS_Sessions { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Item_Measures> Item_Measures { get; set; }
        public virtual DbSet<Item_PriceList> Item_PriceList { get; set; }
        public virtual DbSet<Item> Items { get; set; }
    
        public virtual ObjectResult<Items_by_Category_Result> Items_by_Category(Nullable<int> category_ID)
        {
            var category_IDParameter = category_ID.HasValue ?
                new ObjectParameter("Category_ID", category_ID) :
                new ObjectParameter("Category_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Items_by_Category_Result>("Items_by_Category", category_IDParameter);
        }
    
        public virtual ObjectResult<Items_by_ID_Result> Items_by_ID(Nullable<int> item_ID)
        {
            var item_IDParameter = item_ID.HasValue ?
                new ObjectParameter("Item_ID", item_ID) :
                new ObjectParameter("Item_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Items_by_ID_Result>("Items_by_ID", item_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> POS_Log(string user_Name, string password)
        {
            var user_NameParameter = user_Name != null ?
                new ObjectParameter("User_Name", user_Name) :
                new ObjectParameter("User_Name", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("POS_Log", user_NameParameter, passwordParameter);
        }
    }
}
