//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string S_Group { get; set; }
        public string S_Title { get; set; }
        public string S_Code { get; set; }
        public string S_Value { get; set; }
    }
}
